name: Contracts Publish

on:
  pull_request:
  # push:
  #   tags:
  #     - '*-contracts'

jobs:
  check_tag:
    uses: ./.github/workflows/reusable-check-tag.yml
    with:
      ref: ${{ github.ref }}
    run: echo "package=$PACKAGE"

  tests:
    needs: [check_tag]
    if: ${{ needs.check_tag.outputs.package == 'contracts' }}
    uses: ./.github/workflows/contracts-tests.yml
    secrets:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

  publish:
    needs: [check_tag, tests]
    uses: ./.github/workflows/reusable-publish.yml
    with:
      package: ${{ needs.check_tag.outputs.package }}
      version: ${{ needs.check_tag.outputs.version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
